/**
 * Created by Rahul on 10-Sep-2018
 * 
 */

/**
 * @author Payel
 *
 */
package chess_Game;


public enum Type
{
	CHESS,
	W_ROOK1,W_KNIGHT1,W_BISHOP1,W_KING,W_QUEEN,W_BISHOP2,W_KNIGHT2,W_ROOK2,
	W_PAWN1,W_PAWN2,W_PAWN3,W_PAWN4,W_PAWN5,W_PAWN6,W_PAWN7,W_PAWN8,
	B_ROOK1,B_KNIGHT1,B_BISHOP1,B_KING,B_QUEEN,B_BISHOP2,B_KNIGHT2,B_ROOK2,
	B_PAWN1,B_PAWN2,B_PAWN3,B_PAWN4,B_PAWN5,B_PAWN6,B_PAWN7,B_PAWN8

}